### ISSUE TITLE
使用docker-compose替代docker命令行无效

### ISSUE THREAD

**Issue by xiaoxintang** [MuzhenStudio/Readme#1]
## 配置之后的效果是无法打开网页控制面板
报503

docker-comose配置文件如下
```yaml
version: '3.8'
services:
  jd-longan:
    container_name: jd
    image: shuye72/jd-base:gitee
    volumes:
     - ./mine/config:/jd/config
     - ./mine/log:/jd/log
     - ./scripts:/jd/scripts
    ports:
     - 5678:5678
    environment:
     - ENABLE_HANGUP=true
     - ENABLE_WEB_PANEL=true
    restart: always

```

| 配置的路径没有问题，跟你给的示例的区别就在于一个是命令行一个是docker-compose配置文件(不清楚是否有其他不同)

## 启动后命令行提示如下图
![image](https://user-images.githubusercontent.com/24927686/112725250-38533700-8f52-11eb-8af0-97b20c2ff7b6.png)
## docker命令行启动的情况输出里面好像会多一个东西
![image](https://user-images.githubusercontent.com/24927686/112725326-9b44ce00-8f52-11eb-9269-6936a01744f7.png)

**Comment by xiaoxintang** [comment]
添加`tty:true`解决
```yaml
version: '3.8'
services:
  jd-longan:
    container_name: jd
    image: shuye72/jd-base:gitee
    volumes:
     - ./mine/config:/jd/config
     - ./mine/log:/jd/log
     - ./scripts:/jd/scripts
    ports:
     - 5678:5678
    environment:
     - ENABLE_HANGUP=true
     - ENABLE_WEB_PANEL=true
    restart: always
    tty:true
```
